name: Auth Layer Proxy Tests

on:
    pull_request:
      branches: [ main, release/**]
    push:
      branches: [ main, release/*]
      tags: [ v* ]

jobs:
    proxy-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
              with:
                egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

            - name: Install Lua
              uses: leafo/gh-actions-lua@ea0ae38722c0b45aa4e770f7c4a650c6b26800d0 # v8.0.0
              with:
                luaVersion: '5.3'

            - name: Install LuaRocks
              uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4.3.0

            - name: Install lunatest
              run: luarocks install lunatest
        
            - name: Install luacov
              run: luarocks install luacov

            - name: Install luacov-console
              run: luarocks install luacov-console
        
            - name: Install cjson
              run: luarocks install lua-cjson
        
            - name: Install luasocket
              run: luarocks install luasocket
            
            - name: Run tests
              run: lua test.lua              
              working-directory: auth-layer-proxy/tests
            
            - name: Generate coverage report
              run: luacov
              working-directory: auth-layer-proxy/tests

            - name: Generate Console Report
              run: luacov-console ../filters/ && luacov-console ../filters/ -s  && luacov-console ../filters/ -s > coverage.txt
              working-directory: auth-layer-proxy/tests
